### ISSUE TITLE
Ability to create a sub statter

### ISSUE THREAD

**Issue by mckayb24** [cactus/go-statsd-client#18] opened 2015-10-28 20:45 UTC
I would like to propose a new method for the Statter interface, that would create a SubStatter.
A SubStatter would use the same Sender as the parent Statter but would have it's own prefix.
This would allow users to add instrumentation to utility functions that are used by numerous packages with out having to create a new client.
The Sub method that creates the SubStatter would append an additional prefix to the existing Statter prefix.

I would be happy to implement this if you think it is worthwhile.

**Comment by cactus** [comment] 2015-10-29 03:11
Preface: I am not opposed to the idea, but I am a of course bit leery of changing the interface.

Do note that if a user simply wants to append a prefix to an existing client, they can simply supply their desired append string as part of the stat name.

Example:

~~~
client, _ := NewClient("127.0.0.1:8125", "test-client")

client.Inc("some.prefix.test")
// test-client.some.prefix.test:1|c
~~~

Now, replacing the prefix entirely would not be achievable like this of course. That would require construction of a new client instance. To accomplish that, I think something like what you suggested would need to be implemented, and clients would need to support the creation of a sub-client or a linked-copy of some kind via a  `WithPrefix(string) Statter` method or a `LinedClone() Statter` method. 

Example:

~~~
client, err := NewClient("127.0.0.1:8125", "test-client")
// handle any errors
if err != nil {
    log.Fatal(err)
}

// WithPrefix(string) Statter
client.WithPrefix("my.other.prefix").Inc("test")
// my.other.prefix:1|c
~~~

Where WithPrefix returns a copy of the client statter, but uses the same sender as the original client. If either the original statter or the copy is `Close()`d, any other copies would simply start to return error for any stats sent.

This seem _to me_ to be both a bit heavyweight (given that clients are easy to create), and a possible cause for unexpected behavior -- consider where a consumer closes the client and the main/parent statter simply stops sending metrics.

However, I can certainly see a case where something implements the statter interface, and does some custom "deep magicks" internally, yet wants to add a way for consumers to add their own metric prefixes and utilize the existing client. I am not sure if the use case is strong enough though, to warrant the additional complexity and possibly unexpected (for end users) behaviors.

**Comment by mckayb24** [comment] 2015-10-31 20:30
You are absolutely right about Close leading to confusion. The easiest way to solve this would be to create a second interface for SubStatter that is the same as Statter but is missing the Close method.

I have decided to create a wrapper around the Client and NoopClient structs for my own purposes.
If you decide you do want something like a SubStatter please let me know.

**Comment by stellentus** [comment] 2015-11-04 19:38
I see this feature as being used to append to the prefix rather than replacing it entirely. If someone wants an entirely new prefix, it's reasonable to create a new Client. But what if my code dynamically needs to append complex prefixes?

For example, imagine I have a codebase that tracks trains. I want to track things like `traintracker.detroit.arrivals`, `traintracker.detroit.departures`, `traintracker.newyork.arrivals`, etc.

I'd like to create a new client with the prefix "traintracker". Then I want to instantiate a new `SubStatter` for "detroit", "newyork", etc. I don't know in advance how many, or what their names will be, but I don't want to pass the IP address and initial prefix ("traintracker") to each `SubStatter`. I also don't want my `NewArrivalDepartureTracker` to need to add the city name into the prefix. It should just receive a `Statter` so it can call `s.Inc("departures", i, 1.0)`.
I want to pass `s.NewSubStatterAppendingPrefix("detroit")` (which creates a SubStatter with the prefix "traintracker.detroit") into `ArrivalDepartureTracker`, where `s` is a `statsd.Client` which may have been created in a completely different package, and it might be passed around to be used like this in many places.

The `SubStatter` should not have the `SetPrefix` and `Close` methods. So I propose something like this:

	// StatSender is used to send stats to the statsd server
	type StatSender interface {
		Inc(string, int64, float32) error
		Dec(string, int64, float32) error
		Gauge(string, int64, float32) error
		GaugeDelta(string, int64, float32) error
		Timing(string, int64, float32) error
		TimingDuration(string, time.Duration, float32) error
		Set(string, string, float32) error
		SetInt(string, int64, float32) error
		Raw(string, string, float32) error
	}

	type Statter interface {
		StatSender
		SetPrefix(string)
		Close() error
		NewSubStatterAppendingPrefix() SubStatter
	}

	type SubStatter interface {
		StatSender
		NewSubStatterAppendingPrefix() SubStatter
	}

The names could use some work, but this would otherwise be a fairly straightforward change. The only added complexity for users who don't care about `SubStatter` is that the `Statter` interface now embeds the `StatSender` interface, so it's slightly more complex to understand.

Note that my actual use case involves one or two more nested prefixes than the above example, so it gets to be a real pain to pass around a long prefix. (Imagine `tracker.bus.detroit.arrivals`, `tracker.train.newyork.departures`, `tracker.boat.seattle.stowaways`, etc.)

**Comment by cactus** [comment] 2015-11-04 20:19
I just pushed a branch (`substatter`) with a first stab at this, largely based on what @stellentus suggested. Note that `NewSubStatterAppendingPrefix() SubStatter` is instead `NewSubStatter(string) SubStatter`. Let me know if this would fulfill the requirements, and work as expected.

**Comment by stellentus** [comment] 2015-11-06 19:20
@cactus That would work great for our use case. However, I've thought of another problem. This ends up adding a method to the `Statter` interface, which means that anyone who has implemented their own `Statter` will get a build error if they pull this update. It's fairly easy for them to fix (by implementing `NewSubStatter(string) SubStatter`), but I'm not sure if it's ok to change the API like that?

The alternative, though, is more complex:

	// DataSender is used to send data to a statsd server.
	type DataSender interface {
		Inc(string, int64, float32) error
		Dec(string, int64, float32) error
		Gauge(string, int64, float32) error
		GaugeDelta(string, int64, float32) error
		Timing(string, int64, float32) error
		TimingDuration(string, time.Duration, float32) error
		Set(string, string, float32) error
		SetInt(string, int64, float32) error
		Raw(string, string, float32) error
		SetPrefix(string)
	}

	// Statter is a DataSender which can be closed.
	type Statter interface {
		DataSender
		Close() error
	}

	// SubStatter is a DataSender that can be used to create an additional
	// SubStatter (i.e. a DataSender with an appended prefix).
	type SubStatter interface {
		DataSender
		SubStatter(string) SubStatter
	}

	// RootStatter is the root Statter from which SubStatters can be created.
	// Unlike the SubStatters, it can be closed.
	// If SubStatters are not required, this can be treated as a Statter.
	type RootStatter interface {
		Statter
		SubStatter
	}

Note I moved `SetPrefix(string)` into `DataSender`. (It's debatable whether it belongs there, or in the `Statter` interface.) Now `NewClient` can return a `RootStatter` without breaking anyone's code (since they can still use it as a regular `Statter`, and an existing `Statter` works the same). But this turns 1 interface into 4 interfaces, which is maybe too complex. 
I'm just not sure if it's bad practice to add a method to an existing interface.

**Comment by cactus** [comment] 2015-11-06 19:31
Yeah, breaking the existing interface was one of my initial reservations.

With the branch, I had considered adding a new interface for subbable statters, and keeping the existing statter interface, but I wasn't especially happy with the increased interface complexity. It would have required anyone wanting to make a substatter to do a type conversion, which is not exactly "friendly". ;)

I am going to mull it over a bit more and see how I feel about it -- maybe it will grow on me.

**Comment by stellentus** [comment] 2015-11-06 19:38
Also, @cactus, I'm impressed by how quickly you wrote that code and tests! :)

One note on the tests: none of the tests confirm that it works to create two different SubStatters from the same Client (i.e. `test.sub.gauge:1|g` and also `test.sub2.gauge:1|g`). If there was a bug in Client's `SubStatter(string) SubStatter` implementation (such that it changed the original Client and returned it, rather than creating a new Client), I think the tests wouldn't catch that?
The implementation looks good, so I'm not concerned, but I figured I'd point it out in case you want to add another test. (Or if you want me to add it.)

Also, is there a reason `NoopClient` stores the `prefix`? This is unrelated to this issue, but I noticed it in the diff. If it has reason to store the prefix, maybe the Noop `NewSubStatter` should be updating the prefix? (But I'd be more inclined to just remove the prefix altogether.)
Again, this is a bit pedantic; I'm mostly asking in case I can learn from your reasoning. (I've already learned a lot from your use of reflect in the tests and variadic arguments in `NewNoopClient`.)

**Comment by cactus** [comment] 2015-11-06 21:29
> none of the tests confirm that it works to create two different SubStatters from the same Client (i.e. test.sub.gauge:1|g and also test.sub2.gauge:1|g). If there was a bug in Client's SubStatter(string) SubStatter implementation (such that it changed the original Client and returned it, rather than creating a new Client), I think the tests wouldn't catch that?
> The implementation looks good, so I'm not concerned, but I figured I'd point it out in case you want to add another test. (Or if you want me to add it.)

Ah. Thanks for pointing that out. I will add a test for it.

> Also, is there a reason NoopClient stores the prefix?

I think this was (memory is a bit foggy though) probably a result of an early design choice where I was planning on adding a GetPrefix to the Statter interface. I later decided against -- a true case of YAGNI (you aren't gonna need it) if I ever saw one! Looks like that vestigial code in noop was just never cleaned up afterwards. Feel free to open a pull req against master for that one, if you are so inclined. If not, I can fix it too. :)

> Again, this is a bit pedantic; I'm mostly asking in case I can learn from your reasoning. 

I do not inherently object to well founded pedantry. :P

**Comment by cactus** [comment] 2015-11-06 21:46
Additional test for multiple substatters added.

**Comment by cactus** [comment] 2015-12-04 20:17
merged

**Closed by cactus** 2015-12-04 20:17 UTC
Labels: enhancement
